import type { QuestionTemplate, Topic } from "@/lib/types";

export const TOPICS: Topic[] = [
  {
    id: "design-patterns",
    name: "디자인 패턴",
    description: "GoF 패턴의 목적, 분류, 대표 패턴 구분을 점검합니다.",
    keywords: ["Singleton", "Factory Method", "Observer", "Adapter", "Strategy", "Decorator"],
  },
  {
    id: "diagrams",
    name: "다이어그램 종류",
    description: "UML 구조/행위 다이어그램과 요구사항 분석 산출물을 구분합니다.",
    keywords: ["Use Case", "Class", "Sequence", "Activity", "State", "ERD"],
  },
  {
    id: "osi",
    name: "OSI 7계층",
    description: "계층별 역할, 장비, 프로토콜, 데이터 단위를 연결해 봅니다.",
    keywords: ["Physical", "Data Link", "Network", "Transport", "Session", "Presentation", "Application"],
  },
  {
    id: "coverage",
    name: "커버리지 종류",
    description: "화이트박스 테스트 기준인 문장, 분기, 조건, 경로 커버리지를 비교합니다.",
    keywords: ["Statement", "Branch", "Condition", "Decision", "Path", "MC/DC"],
  },
  {
    id: "security-attacks",
    name: "해킹 공격 종류",
    description: "실기 단답형에 자주 나오는 공격 기법과 방어 개념을 정리합니다.",
    keywords: ["SQL Injection", "XSS", "CSRF", "DoS", "Sniffing", "Phishing", "Ransomware"],
  },
  {
    id: "modern-tech",
    name: "최신 기술 현황",
    description: "클라우드, AI, 데이터, 블록체인, 보안 신기술 용어를 폭넓게 다룹니다.",
    keywords: ["Generative AI", "Edge Computing", "Zero Trust", "MLOps", "Kubernetes", "Digital Twin"],
  },
  {
    id: "software-engineering",
    name: "소프트웨어 개발 방법론",
    description: "전통적/애자일 개발 프로세스 및 SOLID 객체지향 설계 원칙을 이해합니다.",
    keywords: ["Waterfall", "Agile", "XP", "Scrum", "SRP", "OCP", "LSP", "ISP", "DIP"],
  },
  {
    id: "database",
    name: "데이터베이스 구축",
    description: "트랜잭션 ACID 특징, 정규화 절차 및 반정규화 기법을 정리합니다.",
    keywords: ["ACID", "Anomaly", "Normalization", "De-normalization"],
  },
  {
    id: "testing",
    name: "애플리케이션 테스트",
    description: "블랙박스/화이트박스 테스트, 테스트 단계, 살충제 패러독스를 점검합니다.",
    keywords: ["Black Box", "White Box", "Test Levels", "Pesticide Paradox", "Regression"],
  },
];

export const QUESTION_BANK: QuestionTemplate[] = [
  {
    topicId: "design-patterns",
    keyword: "Singleton",
    difficulty: "easy",
    type: "short",
    prompt: "클래스의 인스턴스가 하나만 생성되도록 보장하고 전역 접근점을 제공하는 디자인 패턴은 무엇인가?",
    answer: "Singleton Pattern",
    explanation: "싱글턴은 생성자를 제한하고 정적 메서드 등을 통해 단일 객체에 접근하게 하는 생성 패턴입니다.",
  },
  {
    topicId: "design-patterns",
    keyword: "Factory Method",
    difficulty: "medium",
    type: "multiple-choice",
    prompt: "객체 생성 처리를 서브클래스에 위임해 결합도를 낮추는 패턴으로 가장 적절한 것은?",
    choices: ["Factory Method", "Observer", "Facade", "Proxy"],
    answer: "Factory Method",
    explanation: "팩토리 메서드는 생성할 객체의 구체 클래스를 하위 클래스가 결정하게 합니다.",
  },
  {
    topicId: "design-patterns",
    keyword: "Observer",
    difficulty: "medium",
    type: "scenario",
    prompt: "게시글 변경 시 여러 구독자 화면을 자동으로 갱신하려 한다. 이 요구에 적합한 디자인 패턴은?",
    answer: "Observer Pattern",
    explanation: "옵저버는 주체의 상태 변경을 의존 객체들에게 통지하는 행위 패턴입니다.",
  },
  {
    topicId: "design-patterns",
    keyword: "Adapter",
    difficulty: "hard",
    type: "scenario",
    prompt: "기존 결제 모듈의 인터페이스가 신규 주문 서비스와 맞지 않는다. 기존 코드를 크게 바꾸지 않고 호환시키는 패턴은?",
    answer: "Adapter Pattern",
    explanation: "어댑터는 호환되지 않는 인터페이스 사이를 변환해 기존 객체를 재사용하게 합니다.",
  },
  {
    topicId: "design-patterns",
    keyword: "Strategy",
    difficulty: "hard",
    type: "short",
    prompt: "알고리즘군을 캡슐화하고 실행 시점에 교체할 수 있게 하는 행위 패턴은?",
    answer: "Strategy Pattern",
    explanation: "전략 패턴은 할인 정책, 정렬 방식처럼 교체 가능한 알고리즘을 객체로 분리합니다.",
  },
  {
    topicId: "diagrams",
    keyword: "Use Case",
    difficulty: "easy",
    type: "short",
    prompt: "사용자와 시스템 사이의 상호작용 및 시스템 기능을 외부 관점에서 표현하는 UML 다이어그램은?",
    answer: "Use Case Diagram",
    explanation: "유스케이스 다이어그램은 액터와 유스케이스 관계를 통해 기능 요구사항을 표현합니다.",
  },
  {
    topicId: "diagrams",
    keyword: "Sequence",
    difficulty: "medium",
    type: "multiple-choice",
    prompt: "객체 간 메시지 흐름을 시간 순서대로 표현하는 UML 다이어그램은?",
    choices: ["Class Diagram", "Sequence Diagram", "Deployment Diagram", "Package Diagram"],
    answer: "Sequence Diagram",
    explanation: "시퀀스 다이어그램은 생명선과 메시지로 객체 간 동적 상호작용을 표현합니다.",
  },
  {
    topicId: "diagrams",
    keyword: "Class",
    difficulty: "medium",
    type: "short",
    prompt: "클래스의 속성, 연산, 클래스 간 관계를 정적으로 표현하는 UML 구조 다이어그램은?",
    answer: "Class Diagram",
    explanation: "클래스 다이어그램은 상속, 연관, 집합, 합성 등 정적 구조를 표현합니다.",
  },
  {
    topicId: "diagrams",
    keyword: "Activity",
    difficulty: "hard",
    type: "scenario",
    prompt: "업무 처리 절차의 분기, 병합, 병렬 흐름을 모델링하려 한다. 가장 알맞은 다이어그램은?",
    answer: "Activity Diagram",
    explanation: "활동 다이어그램은 처리 흐름과 제어 흐름을 표현해 업무 프로세스 모델링에 적합합니다.",
  },
  {
    topicId: "osi",
    keyword: "Network",
    difficulty: "easy",
    type: "short",
    prompt: "IP 주소를 기반으로 경로 선택과 패킷 전달을 수행하는 OSI 계층은?",
    answer: "Network Layer",
    explanation: "네트워크 계층은 라우팅과 논리 주소 지정을 담당합니다.",
  },
  {
    topicId: "osi",
    keyword: "Transport",
    difficulty: "medium",
    type: "multiple-choice",
    prompt: "TCP와 UDP가 속하며 종단 간 신뢰성 있는 전송을 담당하는 계층은?",
    choices: ["Data Link Layer", "Network Layer", "Transport Layer", "Presentation Layer"],
    answer: "Transport Layer",
    explanation: "전송 계층은 포트 번호, 흐름 제어, 오류 제어, 세그먼트 전송을 다룹니다.",
  },
  {
    topicId: "osi",
    keyword: "Data Link",
    difficulty: "medium",
    type: "short",
    prompt: "MAC 주소 기반 프레임 전송과 오류 검출을 담당하는 OSI 계층은?",
    answer: "Data Link Layer",
    explanation: "데이터 링크 계층은 인접 노드 간 프레임 전달을 담당하며 스위치와 관련이 깊습니다.",
  },
  {
    topicId: "osi",
    keyword: "Presentation",
    difficulty: "hard",
    type: "scenario",
    prompt: "문자 인코딩 변환, 암호화, 압축과 가장 관련이 깊은 OSI 계층은?",
    answer: "Presentation Layer",
    explanation: "표현 계층은 응용 데이터의 표현 방식 변환, 암호화, 압축을 담당합니다.",
  },
  {
    topicId: "coverage",
    keyword: "Statement",
    difficulty: "easy",
    type: "short",
    prompt: "프로그램 내 모든 실행문이 적어도 한 번 수행되었는지를 측정하는 테스트 커버리지는?",
    answer: "Statement Coverage",
    explanation: "문장 커버리지는 코드의 각 문장이 한 번 이상 실행되는지를 기준으로 합니다.",
  },
  {
    topicId: "coverage",
    keyword: "Branch",
    difficulty: "medium",
    type: "multiple-choice",
    prompt: "if문의 참과 거짓 결과가 각각 한 번 이상 수행되었는지 확인하는 커버리지는?",
    choices: ["Statement Coverage", "Branch Coverage", "Path Coverage", "Loop Coverage"],
    answer: "Branch Coverage",
    explanation: "분기 커버리지는 결정 지점의 모든 분기 결과를 테스트합니다.",
  },
  {
    topicId: "coverage",
    keyword: "Condition",
    difficulty: "medium",
    type: "short",
    prompt: "복합 조건식에서 각 개별 조건이 참과 거짓을 모두 갖도록 하는 커버리지는?",
    answer: "Condition Coverage",
    explanation: "조건 커버리지는 결정 전체보다 개별 조건의 참/거짓 수행 여부에 집중합니다.",
  },
  {
    topicId: "coverage",
    keyword: "Path",
    difficulty: "hard",
    type: "scenario",
    prompt: "프로그램의 가능한 모든 실행 경로를 테스트하려는 기준은 무엇인가?",
    answer: "Path Coverage",
    explanation: "경로 커버리지는 가장 강한 기준 중 하나지만 경로 수가 급증해 현실적 비용이 큽니다.",
  },
  {
    topicId: "security-attacks",
    keyword: "SQL Injection",
    difficulty: "easy",
    type: "short",
    prompt: "입력값에 악의적인 SQL 문을 삽입해 DB를 비정상 조작하는 공격은?",
    answer: "SQL Injection",
    explanation: "SQL 삽입 공격은 파라미터 바인딩, 입력 검증, ORM 사용 등으로 완화할 수 있습니다.",
  },
  {
    topicId: "security-attacks",
    keyword: "XSS",
    difficulty: "medium",
    type: "multiple-choice",
    prompt: "웹 페이지에 악성 스크립트를 삽입해 사용자의 브라우저에서 실행시키는 공격은?",
    choices: ["CSRF", "XSS", "Smurf", "Brute Force"],
    answer: "XSS",
    explanation: "크로스 사이트 스크립팅은 출력 인코딩, CSP, 입력 검증으로 방어합니다.",
  },
  {
    topicId: "security-attacks",
    keyword: "CSRF",
    difficulty: "medium",
    type: "short",
    prompt: "인증된 사용자의 권한을 이용해 사용자가 의도하지 않은 요청을 보내게 하는 공격은?",
    answer: "CSRF",
    explanation: "CSRF는 토큰 검증, SameSite 쿠키, 재인증 요구 등으로 줄일 수 있습니다.",
  },
  {
    topicId: "security-attacks",
    keyword: "DoS",
    difficulty: "hard",
    type: "scenario",
    prompt: "대량의 트래픽이나 요청으로 서비스 자원을 고갈시켜 정상 이용을 방해하는 공격은?",
    answer: "DoS 또는 DDoS",
    explanation: "분산된 여러 장비가 동시에 공격하면 DDoS이며, 트래픽 필터링과 rate limit이 중요합니다.",
  },
  {
    topicId: "modern-tech",
    keyword: "Generative AI",
    difficulty: "easy",
    type: "short",
    prompt: "텍스트, 이미지, 코드 등 새로운 콘텐츠를 생성하는 인공지능 기술을 무엇이라 하는가?",
    answer: "Generative AI",
    explanation: "생성형 AI는 학습한 패턴을 바탕으로 새 콘텐츠를 생성하는 기술입니다.",
  },
  {
    topicId: "modern-tech",
    keyword: "Zero Trust",
    difficulty: "medium",
    type: "multiple-choice",
    prompt: "내부망도 기본적으로 신뢰하지 않고 모든 접근을 지속 검증하는 보안 모델은?",
    choices: ["Zero Trust", "VPN Tunneling", "Waterfall", "RAID"],
    answer: "Zero Trust",
    explanation: "제로 트러스트는 명시적 검증, 최소 권한, 침해 가정을 핵심 원칙으로 합니다.",
  },
  {
    topicId: "modern-tech",
    keyword: "MLOps",
    difficulty: "medium",
    type: "short",
    prompt: "머신러닝 모델의 개발, 배포, 운영, 모니터링을 자동화하고 관리하는 방법론은?",
    answer: "MLOps",
    explanation: "MLOps는 ML과 DevOps 관행을 결합해 모델 생명주기를 안정적으로 운영합니다.",
  },
  {
    topicId: "modern-tech",
    keyword: "Digital Twin",
    difficulty: "hard",
    type: "scenario",
    prompt: "현실 세계의 설비나 공정을 가상 공간에 복제해 시뮬레이션과 분석에 활용하는 기술은?",
    answer: "Digital Twin",
    explanation: "디지털 트윈은 현실 객체의 상태 데이터를 반영한 가상 모델로 예측과 최적화에 쓰입니다.",
  },
  {
    topicId: "software-engineering",
    keyword: "Agile",
    difficulty: "easy",
    type: "short",
    prompt: "고객과의 소통과 변화에 대한 빠른 대응을 중요하게 생각하는 반복적이고 점진적인 소프트웨어 개발 방법론의 총칭은 무엇인가?",
    answer: "Agile",
    explanation: "애자일 방법론은 계획 중심의 폭포수 모델에 대비되는 고객 중심, 변화 대응 중심의 개발론입니다.",
  },
  {
    topicId: "software-engineering",
    keyword: "OCP",
    difficulty: "medium",
    type: "multiple-choice",
    prompt: "객체지향 설계 5대 원칙(SOLID) 중 '소프트웨어 개체는 확장에 대해 열려 있어야 하고 수정에 대해서는 닫혀 있어야 한다'는 원칙은 무엇인가?",
    choices: [
      "단일 책임 원칙 (Single Responsibility Principle)",
      "개방-폐쇄 원칙 (Open-Closed Principle)",
      "리스코프 치환 원칙 (Liskov Substitution Principle)",
      "인터페이스 분리 원칙 (Interface Segregation Principle)",
    ],
    answer: "개방-폐쇄 원칙 (Open-Closed Principle)",
    explanation: "개방-폐쇄 원칙(OCP)은 기존 코드를 수정하지 않고 확장이 가능해야 함을 의미합니다.",
  },
  {
    topicId: "software-engineering",
    keyword: "Scrum",
    difficulty: "hard",
    type: "scenario",
    prompt: "한 프로젝트 팀이 3주간의 '스프린트'를 주기로 삼아 개발하고 매일 아침 간단히 진행 상황과 장애 요소를 공유하고 있다. 이 애자일 기법은 무엇인가?",
    answer: "Scrum",
    explanation: "스크럼은 PO, 스크럼 마스터와 함께 주기적인 스프린트와 일일 스크럼 미팅을 통해 협업하는 관리 프레임워크입니다.",
  },
  {
    topicId: "database",
    keyword: "ACID",
    difficulty: "easy",
    type: "short",
    prompt: "트랜잭션 연산이 데이터베이스에 모두 반영되거나 아예 반영되지 않아야 하는(All or Nothing) 원자성을 포함하는 트랜잭션의 4대 특징을 일컫는 약어는 무엇인가?",
    answer: "ACID",
    explanation: "트랜잭션의 4대 특징은 Atomicity(원자성), Consistency(일관성), Isolation(고립성), Durability(영속성)의 앞글자를 딴 ACID입니다.",
  },
  {
    topicId: "database",
    keyword: "Normalization",
    difficulty: "medium",
    type: "multiple-choice",
    prompt: "관계형 데이터베이스 설계에서 이행적 함수 종속성(A->B, B->C 일 때 A->C)을 제거하여 이상현상을 방지하는 정규화 단계는 무엇인가?",
    choices: ["제 1정규형(1NF)", "제 2정규형(2NF)", "제 3정규형(3NF)", "보이스-코드 정규형(BCNF)"],
    answer: "제 3정규형(3NF)",
    explanation: "제3정규형은 주 식별자 이외의 속성 간 이행적 함수 종속성을 제거하는 단계입니다.",
  },
  {
    topicId: "testing",
    keyword: "Pesticide Paradox",
    difficulty: "medium",
    type: "short",
    prompt: "동일한 테스트 케이스로 반복 테스트를 수행하면 더 이상 새로운 결함을 찾을 수 없으므로, 테스트 케이스를 주기적으로 갱신해야 한다는 테스트의 원리는 무엇인가?",
    answer: "Pesticide Paradox",
    explanation: "살충제 패러독스는 테스트 케이스의 타당성을 지속적으로 검토하고 개선해야 함을 강조하는 개념입니다.",
  },
  {
    topicId: "testing",
    keyword: "Regression",
    difficulty: "hard",
    type: "scenario",
    prompt: "최근 버그 수정을 거친 소프트웨어 모듈이 기존에 정상 작동하던 다른 영역에 부작용을 유발하지 않았는지 보증하기 위해 수행하는 재테스트 기법은 무엇인가?",
    answer: "Regression Test",
    explanation: "회귀 테스트(Regression Test)는 소스 코드 수정 후 발생할 수 있는 부작용을 검출하기 위해 수행하는 재시험입니다.",
  },
];
